### PR TITLE
Fix ID conflict and maven

### LINKED ISSUE #2: duplication ID
with the update of gregtech 1.16.0.750 there is a duplication id which makes crash the game

with tTime: 6/30/21 11:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Energistics (gregtechenergistics)
Caused by: java.lang.IllegalArgumentException: Tried to reassign id 40 to gregtech.api.cover.CoverDefinition@33e49947 (gregtechenergistics:ae2.interface.lv), but it is already assigned to gregtech.api.cover.CoverDefinition@18f687c0 (gregtech:fluid.regulator.lv)!
	at gregtech.api.util.GTControlledRegistry.register(GTControlledRegistry.java:50)
	at gregtech.api.cover.CoverDefinition.registerCover(CoverDefinition.java:28)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.registerBehavior(CoverBehaviors.java:41)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.registerStockerCover(CoverBehaviors.java:34)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.init(CoverBehaviors.java:19)
	at com.soliddowant.gregtechenergistics.CommonProxy.init(CommonProxy.java:24)
	at com.soliddowant.gregtechenergistics.ClientProxy.init(ClientProxy.java:19)
	at com.soliddowant.gregtechenergistics.GregTechEnergisticsMod.init(GregTechEnergisticsMod.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)e update of gregtech 1.16.0.750 there is a duplication id which makes crash the game

### PR DESCRIPTION
**Pull request by magcicada**
Fixes #2 and fix maven in build.gradle.

### CODE REVIEW

**Comment by solidDoWant** [comment]
Thanks @magcicada. Any suggestions on how to either provide an upgrade path for existing users, or some kind of a warning? I'd prefer not to break existing worlds when upgrading if possible

**Comment by Ackmard** [comment]
I downloaded your version but the stocker terminal has a missing texture background. I was just testing it in a creative world so I'm not sure if it has anything to do with the terminal being giver from the creative inventory rather than being crafted.

**Comment by magcicada** [comment]
@Ackmard You are using the [Trousers version AE2](https://github.com/PrototypeTrousers/Applied-Energistics-2),it deleted this [textures](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/resources/assets/appliedenergistics2/textures/guis/interfaceterminal.png),and [here](https://github.com/solidDoWant/GregTech-Energistics/blob/693cf454e527ac22c731d08baf3e1878aa962a2f/src/main/java/com/soliddowant/gregtechenergistics/gui/StockerTerminalGuiContainer.java#L121) need use it ,so the gui has a missing texture background.

**Comment by Ackmard** [comment]
@magcicada So is there an easy way to fix this?

**Comment by Ackmard** [comment]
@magcicada I just added the texture back in the mod and now it's working. Thanks.

**Comment by magcicada** [comment]
@Ackmard Need use this [old one](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/resources/assets/appliedenergistics2/textures/guis/interfaceterminal.png),or you will get a texture issue.

**Comment by accessdenied0** [comment]
Excuse my question but: 
I'm a bit confused: Is there a working version?

**Comment by warjort** [comment]
> Thanks @magcicada. Any suggestions on how to either provide an upgrade path for existing users, or some kind of a warning? I'd prefer not to break existing worlds when upgrading if possible

This won't break existing worlds as such.
The number that is changed is only used for network requests.
When loading/saving covers it uses the the coverId which is a ResourceLocation that hasn't changed in this PR.

What would break is somebody trying to run a client with an older version without this change connected to a server with this change or vice-versa. They would disagree on the network id of the covers.
Running different versions between the client and server usually isn't supported anyway.

**Comment by solidDoWant** [comment]
Ah thanks. Merged. I'll upload your release from magcicada:main to curseforge in a few minutes.

**Pull request merged**
